export const DARK_PATTERN_TYPES = [
  {
    id: 'hidden_costs',
    name: 'Hidden Costs',
    description: 'Additional fees revealed only at final checkout',
    severity: 'high',
  },
  {
    id: 'forced_action',
    name: 'Forced Action',
    description: 'User must perform unwanted action to proceed',
    severity: 'high',
  },
  {
    id: 'confirmshaming',
    name: 'Confirmshaming',
    description: 'Shames user into accepting something they don\'t want',
    severity: 'medium',
  },
  {
    id: 'sneak_into_basket',
    name: 'Sneak into Basket',
    description: 'Items added to cart without explicit user consent',
    severity: 'high',
  },
  {
    id: 'fake_timer',
    name: 'Fake Countdown Timer',
    description: 'Artificial urgency with fake or resetting timers',
    severity: 'medium',
  },
  {
    id: 'misdirection',
    name: 'Misdirection',
    description: 'Focus drawn away from important information',
    severity: 'medium',
  },
  {
    id: 'privacy_zuckering',
    name: 'Privacy Manipulation',
    description: 'Confusing options that lead to sharing more data',
    severity: 'high',
  },
  {
    id: 'obstruction',
    name: 'Obstruction',
    description: 'Making simple tasks difficult or time-consuming',
    severity: 'medium',
  },
  {
    id: 'roach_motel',
    name: 'Roach Motel',
    description: 'Easy to get in, hard to get out (cancel/opt-out)',
    severity: 'high',
  },
  {
    id: 'preselected_checkbox',
    name: 'Pre-selected Checkboxes',
    description: 'Opt-in checkboxes pre-selected by default',
    severity: 'medium',
  },
  {
    id: 'bait_and_switch',
    name: 'Bait and Switch',
    description: 'Promises one thing but delivers another',
    severity: 'high',
  },
  {
    id: 'disguised_ads',
    name: 'Disguised Ads',
    description: 'Ads that look like content or navigation',
    severity: 'low',
  },
  {
    id: 'friend_spam',
    name: 'Friend Spam',
    description: 'Abusing contacts for viral growth',
    severity: 'medium',
  },
  {
    id: 'trick_questions',
    name: 'Trick Questions',
    description: 'Confusing wording to get unintended consent',
    severity: 'medium',
  },
] as const;

export const DARK_PATTERN_PHRASES: Record<string, string[]> = {
  confirmshaming: [
    'no thanks',
    "i don't want",
    'i prefer to',
    'no, i prefer not',
    'no thanks, i',
    "no thanks, i'd rather not",
    'no thanks, i prefer to pay',
    'no thanks',
    'skip trial',
    'i\'ll pay full price',
    'deals are not for me',
    'i don\'t like saving money',
    'no thanks',
    'i\'ll pass',
    'not interested',
    'leave this page',
    'stay unverified',
    'continue without',
    'no thanks',
  ],
  fake_timer: [
    'limited time',
    'hurry',
    'act now',
    'ends soon',
    'expires in',
    'only',
    'minutes left',
    'seconds left',
    'last chance',
    'final chance',
    'don\'t miss',
    'time running out',
    'offer expires',
    'sale ends',
    'today only',
    'deadline',
    'countdown',
  ],
  hidden_costs: [
    'handling fee',
    'service charge',
    'processing fee',
    'convenience fee',
    'booking fee',
    'order fee',
    'delivery surcharge',
    'administrative fee',
    'resort fee',
    'destination fee',
    'mandatory fee',
    'additional charges apply',
    'taxes and fees',
    'total may vary',
    'plus applicable fees',
  ],
  forced_action: [
    'must accept',
    'required to continue',
    'register to see price',
    'sign up to view',
    'create an account to',
    'login to see',
    'subscribe to access',
    'upgrade to view',
    'premium only',
    'members only',
    'verification required',
  ],
  sneak_into_basket: [
    'added to your order',
    'we added',
    'included in your cart',
    'free trial added',
    'special offer added',
    'gift wrapping',
    'recommended add-on',
    'customers also bought',
    'frequently bought together',
    'auto-renew',
    'subscription added',
  ],
  misdirection: [
    'x users viewing',
    'only x left',
    'selling fast',
    'trending',
    'popular choice',
    'bestseller',
    'limited stock',
    'almost gone',
    'high demand',
    'exclusive offer',
    'members get more',
    'flash deal',
  ],
  privacy_zuckering: [
    'improve your experience',
    'personalized ads',
    'accept all cookies',
    'we use cookies',
    'privacy settings',
    'data collection',
    'tracking preferences',
    'personalized content',
    'tailored experience',
    'relevant ads',
    'share with partners',
    'third-party cookies',
  ],
  obstruction: [
    'call to cancel',
    'contact support',
    'difficult to cancel',
    'cannot cancel online',
    'no cancel button',
    'submit a request',
    'wait 24 hours',
    'processing time',
    'pending cancellation',
    'review period',
    'confirmation required',
  ],
  roach_motel: [
    'easy sign up',
    'quick registration',
    'instant access',
    'one-click signup',
    'join now',
    'get started',
    'free account',
    'to cancel:',
    'unsubscribe:',
    'opt-out:',
    'how to delete',
    'close account',
  ],
  preselected_checkbox: [
    'newsletter',
    'email updates',
    'marketing emails',
    'receive offers',
    'special promotions',
    'partner offers',
    'agree to terms',
    'accept privacy',
    'remember me',
    'stay signed in',
    'auto-renew',
    'subscription',
  ],
  bait_and_switch: [
    'as low as',
    'starting from',
    'up to',
    'or similar',
    'from only',
    'selected items',
    'limited availability',
    'subject to availability',
    'while supplies last',
    'exclusions apply',
    'conditions apply',
  ],
  disguised_ads: [
    'sponsored',
    'promoted',
    'ad',
    'advertisement',
    'partner content',
    'recommended for you',
    'you may also like',
    'related content',
    'featured',
  ],
};

export const SEVERITY_COLORS = {
  low: { bg: 'bg-yellow-500', text: 'text-yellow-500', light: 'bg-yellow-100' },
  medium: { bg: 'bg-orange-500', text: 'text-orange-500', light: 'bg-orange-100' },
  high: { bg: 'bg-red-500', text: 'text-red-500', light: 'bg-red-100' },
} as const;

export const PATTERN_ICONS: Record<string, string> = {
  hidden_costs: 'DollarSign',
  forced_action: 'MousePointer',
  confirmshaming: 'MessageCircle',
  sneak_into_basket: 'ShoppingCart',
  fake_timer: 'Timer',
  misdirection: 'ArrowRight',
  privacy_zuckering: 'Lock',
  obstruction: 'XCircle',
  roach_motel: 'LogOut',
  preselected_checkbox: 'CheckSquare',
  bait_and_switch: 'RefreshCw',
  disguised_ads: 'Eye',
  friend_spam: 'Users',
  trick_questions: 'HelpCircle',
};
